### ISSUE TITLE
add search and pages filter to add group

### ISSUE THREAD

**Issue by DeadManPoe** [dsd-meetme/frontend#18]

**Comment by DeadManPoe** [comment]
Simple pagination has been implement and has been in part added to plunner. Simple pagination means that we do not limit the number of page numbers displayed on the bottom of the container of objects

**Comment by carduz** [comment]
we have also to implement pagination on the server side via GET query (?page=1&elementsperpage=10)

**Comment by DeadManPoe** [comment]
Time ago u said that was not really an overhead to download alla the data on the client. I would prefer  not to implement  that since is another thing to do but if its really necessary  u can do it

**Comment by carduz** [comment]
you right. I think that this is needed only for meetings and timeslots, we need a time filter. what do you think?
