### ISSUE TITLE
Planning meetings

### ISSUE THREAD

**Issue by carduz** [dsd-meetme/frontend#45]
the planing of a meeting doesn't work
![schermata del 2016-01-07 02-19-11](https://cloud.githubusercontent.com/assets/10631614/12159731/1f0afbea-b4e5-11e5-9194-08b24387b42f.png)

If it had worked, would meetings constraints have worked?

**Comment by carduz** [comment]
like https://github.com/dsd-meetme/backend/issues/66 or meeting inside one week

**Comment by DeadManPoe** [comment]
Fixed

**Comment by carduz** [comment]
all constraints?
