### ISSUE TITLE
Avoid duplicates

### ISSUE THREAD

**Issue by carduz** [dsd-meetme/frontend#6]
if we use jquery via npm we shouldn't put the library on git  
if we use sass we should put on git only the sass not the 'compiled' css

**Comment by jean-barre** [comment]
It means not committing /node_modules and /assets/css.
Is it possible to put an automatic exception for those directories?
Jean

**Comment by carduz** [comment]
I have already set .gitignore that excludes 'node_modules'
to perform the install automatically it's enought add on git_reciever the following line
system('npm install');
